from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 877)
        MainWindow.setStyleSheet("background-color: #fffcfc")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(22, -1, 22, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background: none")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.inputs = QtWidgets.QWidget(self.centralwidget)
        self.inputs.setObjectName("inputs")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inputs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_timer = QtWidgets.QTextEdit(self.inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_timer.sizePolicy().hasHeightForWidth())
        self.main_timer.setSizePolicy(sizePolicy)
        self.main_timer.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        self.main_timer.setFont(font)
        self.main_timer.setStyleSheet("background-color: #f1f1f1; border:none; border-radius: 20px")
        self.main_timer.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.main_timer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_timer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_timer.setTabChangesFocus(True)
        self.main_timer.setObjectName("main_timer")
        self.verticalLayout.addWidget(self.main_timer)
        self.main_timer_2 = QtWidgets.QTextEdit(self.inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_timer_2.sizePolicy().hasHeightForWidth())
        self.main_timer_2.setSizePolicy(sizePolicy)
        self.main_timer_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        self.main_timer_2.setFont(font)
        self.main_timer_2.setStyleSheet("background-color: #f1f1f1; border:none; border-radius: 20px")
        self.main_timer_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.main_timer_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_timer_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_timer_2.setTabChangesFocus(True)
        self.main_timer_2.setObjectName("main_timer_2")
        self.verticalLayout.addWidget(self.main_timer_2)
        self.main_timer_3 = QtWidgets.QTextEdit(self.inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_timer_3.sizePolicy().hasHeightForWidth())
        self.main_timer_3.setSizePolicy(sizePolicy)
        self.main_timer_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        self.main_timer_3.setFont(font)
        self.main_timer_3.setStyleSheet("background-color: #f1f1f1; border:none; border-radius: 20px")
        self.main_timer_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.main_timer_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_timer_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_timer_3.setTabChangesFocus(True)
        self.main_timer_3.setObjectName("main_timer_3")
        self.verticalLayout.addWidget(self.main_timer_3)
        self.gridLayout.addWidget(self.inputs, 2, 0, 1, 1)
        self.main_timer_label = QtWidgets.QLabel(self.centralwidget)
        self.main_timer_label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(44)
        self.main_timer_label.setFont(font)
        self.main_timer_label.setStyleSheet("background-color: #f1f1f1; border:none; border-radius: 20px")
        self.main_timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_timer_label.setObjectName("main_timer_label")
        self.gridLayout.addWidget(self.main_timer_label, 4, 0, 1, 1)
        self.buttons = QtWidgets.QWidget(self.centralwidget)
        self.buttons.setMinimumSize(QtCore.QSize(476, 480))
        self.buttons.setObjectName("buttons")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.buttons)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.pushButton = QtWidgets.QPushButton(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(125, 125))
        self.pushButton.setStyleSheet("QPushButton::disabled{background-color:lightgrey;} QPushButton {border: none; color: white; background-color: #514cff; border-radius: 20px } QPushButton::hover{ background-color: #6c67ff;}")
        self.pushButton.setObjectName("pushButton")
        self.buttons_layout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMaximumSize(QtCore.QSize(125, 125))
        self.pushButton_3.setStyleSheet("QPushButton::disabled{background-color:lightgrey;} QPushButton {border: none; color: white; background-color: #514cff; border-radius: 20px } QPushButton::hover{ background-color: #6c67ff;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttons_layout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(125, 125))
        self.pushButton_2.setStyleSheet("QPushButton::disabled{background-color:lightgrey;} QPushButton {border: none; color: white; background-color: red; border-radius: 20px } QPushButton::hover{ background-color: #750000;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttons_layout.addWidget(self.pushButton_2)
        self.gridLayout_2.addLayout(self.buttons_layout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.buttons, 5, 0, 1, 1)
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setStyleSheet("color:red")
        self.error_label.setObjectName("error_label")
        self.gridLayout.addWidget(self.error_label, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pomodoro timer"))
        self.label.setText(_translate("MainWindow", "Pomodoro!"))
        self.main_timer.setPlaceholderText(_translate("MainWindow", "Tiempo concentración (MIN)"))
        self.main_timer_2.setPlaceholderText(_translate("MainWindow", "Tiempo descanso (MIN)"))
        self.main_timer_3.setPlaceholderText(_translate("MainWindow", "Tiempo descanso largo (MIN)"))
        self.main_timer_label.setText(_translate("MainWindow", "1:20:31"))
        self.pushButton.setText(_translate("MainWindow", "Iniciar"))
        self.pushButton_3.setText(_translate("MainWindow", "Finalizar fase"))
        self.pushButton_2.setText(_translate("MainWindow", "Detener"))
        self.error_label.setText(_translate("MainWindow", "Por favor introduzca el tiempo en un máximo de 8 dígitos sin decimales (Minutos)"))